### ISSUE TITLE
mvtimageryprovider怎么添加请求头

### ISSUE THREAD

**Issue by xytczh** [kikitte/MVTImageryProvider#10]
请问mvtimageryprovider怎么添加请求头headers 中认证信息？

**Comment by kikitte** [comment]
mapbox gl js 不支持每个瓦片请求添加请求头，可以自行下载https://github.com/kikitte/Mapbox-vector-tiles-basic-js-renderer 修改自定义实现添加header。另一种方式可以考虑修改认证方式，类似天地图将认证信息放入瓦片url的查询参数(query paramater)中，比如`https://api.maptiler.com/tiles/v3/{z}/{x}/{y}.pbf?key=pSHUA9sSkNny3iqoWG4P`中，key就为认证信息。

**Comment by kikitte** [comment]
@xytczh 现在已经支持每个瓦片自定义请求头了，详情可见README和example里提供的例子。
