### ISSUE TITLE
不能正确加载geoserver发布的矢量瓦片

### ISSUE THREAD

**Issue by yuexushuang** [kikitte/MVTImageryProvider#14]
尝试使用RESTFUL方式加载geoserver发布的矢量瓦片，出现 Column out of range 的问题，尝试使用3857或4326发布矢量瓦片都返回这个错误
![1660178520541](https://user-images.githubusercontent.com/13834205/184046398-29f9ae4d-af24-43cc-bf97-a29b3a5c3b77.png)
![image](https://user-images.githubusercontent.com/13834205/184046349-ce82eee2-2191-4c01-a90c-2a8d41302a51.png)

以下为style配置代码：
其中瓦片地址为 
http://127.0.0.1:8930/geoserver/gwc/service/wmts?REQUEST=GetTile&SERVICE=WMTS&VERSION=1.0.0&LAYER=water:catchments5&STYLE=&TILEMATRIX=EPSG:900913:{z}&TILEMATRIXSET=EPSG:900913&FORMAT=application/json&TILECOL={x}&TILEROW={y}

![1660178387734](https://user-images.githubusercontent.com/13834205/184046234-4ab92751-7a2f-4489-8abe-dc326630dc83.png)

**Comment by kikitte** [comment]
MVTImageryProvider由于使用mapbox渲染矢量瓦片，因此只支持[Mapbox vector tile](https://github.com/mapbox/vector-tile-spec)格式瓦片，截图中的format表明矢量瓦片格式为JSON，因此即使没有`Column out of range`报错也能正常使用。另外TileMatrixSet也只能使用截图中所示的EPSG:900913，即3857。如果更改完格式后仍无法加载，可以进一步查看数据源范围是否真的较小，使用一个瓦片就能存储，正如上述报错中提及：最小瓦片列编号和最大都为52，即意味着该矢量数据仅由这单个瓦片存储。

**Comment by yuexushuang** [comment]
感谢！问题已经解决。在source中添加参数"scheme": "tms"，并把tile url 设置为 http://host/geoserver/gwc/service/tms/1.0.0/layername@EPSG%3A3857@pbf/{z}/{x}/{y}.pbf

**Comment by RunBoo** [comment]
@kikitte 请问这个库目前是不是只能加载3857坐标系的MVT服务？
