### ISSUE TITLE
作者您好，我们项目中使用了您的库，但是我有几个疑问，向您请教，期待回复。

### ISSUE THREAD

**Issue by wh1246935943** [kikitte/MVTImageryProvider#26]
1、MVTImageryProvider能在cesium中渲染矢量图的原理是将矢量数据通过MVTImageryProvider转换为栅格图，通过cesium的方法添加到地图展示，cesium最终加载的是栅格图.
2、我们项目中未来会做符号化相关的内容，所以我有一个关心点： 符号化相关的东西，比如绘制图形，添加符号等，这都是cesium 的api来实现，和MVTImageryProvider是无关的。
3、MVTImageryProvider不涉及符号化，且不会影响符号化相关的实现，从您的源码来看，也并不有提供其他数据操作的Api，其只是瓦片的展示。

以上我的描述是否正确，谢谢。

**Comment by kikitte** [comment]
你的理解正确，MVTImageryProvider不会影响Cesium。

**Comment by wh1246935943** [comment]
您好，当我调用 const provider = new MVTImageryProvider({ style: exampleStyle })
exampleStyle的内容是： 
```
{
...
"sources": {
        "test_10001": {
            "type": "vector",
            "url": "http://172.16.20.37:7010/sj_vector/v6/api/dataservice/10001.json?ak=mf72ff9295c740ec0f37e61433e8a3ad8d&access_token=undefined"
        }
    }
}
```
从控制台看，这个请求正常发起，也返回成功了http://172.16.20.37:7010/sj_vector/v6/api/dataservice/10001.json?ak=mf72ff9295c740ec0f37e61433e8a3ad8d&access_token=undefined
返回报文如下：
![image](https://github.com/kikitte/MVTImageryProvider/assets/26916703/a64a02fb-123c-46b0-8274-ebe8f618bef2)

因为我们服务返回的tiles中的url不是完整的，否则 .pbf 的请请求地址是错误的，如下：
![image](https://github.com/kikitte/MVTImageryProvider/assets/26916703/1bcff789-0cb7-426c-80b6-1705f52338c6)

因此我要将返回数据的tiles列表中sjtemp://替换成正确的服务地址，那么我从代码中应该怎么拿到这个数据呢。
