### ISSUE TITLE
请问 地图放大  报这个bug什么问题呢？？？

### ISSUE THREAD

**Issue by lzp0070007** [kikitte/MVTImageryProvider#28]
"mbtiles": {
            "type": "vector",
            "tiles": [
                'http://localhost:3000/aa.mbtiles/{z}/{x}/{y}.pbf'
            ],
        },

{
            "id": "hd_bj_0208",
            "type": "circle",
            "source": "mbtiles",
            "source-layer": "hd_bj_0208"
        },

![1694673967405](https://github.com/kikitte/MVTImageryProvider/assets/5045130/3172ced8-d1a4-4636-b12c-297d01aa94de)

**Comment by kikitte** [comment]
信息不足，最好提供可重复案例。当前看错看起来和MVTImageryProvider没有关系。

**Comment by lzp0070007** [comment]
可能是我切片数据有问题  用qgis切成 mbtiles 发布就会出现这种情况   但是用Martin直接连pg库发布 就没这个bug了
