### ISSUE TITLE
注记似乎没办法显示中文

### ISSUE THREAD

**Issue by hr0109** [kikitte/MVTImageryProvider#3]
openmaptiles.org的数据源，注记为英文时可以正常显示，把text-field改为{name:zh}则全部无法显示，求助

**Comment by kikitte** [comment]
最好是能提供造成这个问题的代码样例。
我这边测试使用openmaptiles.org能显示中文注记，仓库更新了Example2使用了这个网站的一个基础样式。
![image](https://user-images.githubusercontent.com/23274684/133890953-fc0318f3-fc06-4151-bb99-3b51e9070935.png)

**Comment by hr0109** [comment]
我反复测试了一下，似乎问题主要在 https://maputnik.github.io/osm-liberty/style.json 这个样式上出现，而且触发的条件也不在于中文与否，部分英文标签也触发了标签消失问题。

maputnik  osm-liberty
<img width="818" alt="Screenshot 2021-09-21 100821" src="https://user-images.githubusercontent.com/30460774/134101313-36a2be3e-969b-42d4-ad44-fd7aa7031ea5.png">

MVTImageryProvider osm-liberty
<img width="962" alt="Screenshot 2021-09-21 100745" src="https://user-images.githubusercontent.com/30460774/134101437-37c887c8-7fa0-4281-840a-fe96042de404.png">


另外还发现奇怪的问题，路网线宽似乎太粗了，是什么原因导致的呢？

maputnik basic
<img width="800" alt="Screenshot 2021-09-21 100915" src="https://user-images.githubusercontent.com/30460774/134101483-53157c0a-e137-4679-898d-979adef06ac8.png">

MVTImageryProvider basic
![](https://user-images.githubusercontent.com/23274684/133890953-fc0318f3-fc06-4151-bb99-3b51e9070935.png)


顺祝中秋快乐！感谢！

**Comment by kikitte** [comment]
@hr0109 这个样式 https://maputnik.github.io/osm-liberty/style.json 里面有两个地方需要提供key，其中一个是字体文件的url，应该替换掉这些key占位字符串为真实的key才能访问到字体文件以正确渲染标签。
![image](https://user-images.githubusercontent.com/23274684/134356974-a3c6d0a4-a63b-42ee-895f-b7328565a053.png)

至于路网渲染感觉跟mapbox-gl依赖相关，这方面我没多少涉及，还需要深入看看。

**Comment by hr0109** [comment]
key的话直接使用maputnik提供的公用token就行，KDhMfHvorAFkFe64wlZb
basic样式也是使用的这个key

您可以看到右侧那个East china sea就是能显示出来的，f12查看请求也都是成功的

我也感觉可能和依赖有关系，感觉解决起来不容易

**Comment by kikitte** [comment]
@hr0109 我验证过，获取style object后把原来需要key的地方替换掉就连可以正常显示标注了。

**Comment by kikitte** [comment]
@hr0109 问题出现在Mapbox basic render渲染时总是使用zoom 16，导致所有依赖zoom层级的图层属性(比如线条宽度)总是在16的层级下进行计算，这个层级下道路计算得到的宽度大约是16.4px所以看起来比较粗而且不会随着层级改变。目前已经修正这种情况，每次渲染之前都会根据当前渲染的瓦片更新zoom，此项修改已经提交到仓库。感谢反馈！
以下是效果图，看起来好多了。
![image](https://user-images.githubusercontent.com/23274684/135301183-67f3b4ab-055a-4aca-bb36-541517fea062.png)
![image](https://user-images.githubusercontent.com/23274684/135301364-51dc6afe-61cd-4a06-9c93-690a13687474.png)

**Comment by hr0109** [comment]
非常感谢！
