### ISSUE TITLE
根据visibility来控制图层显隐，隐藏图层后，cesium的球上会有隐藏的图层的部分

### ISSUE THREAD

**Issue by Luxcy** [kikitte/MVTImageryProvider#4]
根据addImageryProvider来添加图层，顺利上球
但是用visibility来控制图层显隐时，有时候隐藏图层后，cesium的球上还会有隐藏的图层的部分。
请问有什么比较好的解决方案吗？

**Comment by kikitte** [comment]
@Luxcy 添加完矢量瓦片图层后参照[Cesium ImageryLayer](https://cesium.com/downloads/cesiumjs/releases/1.61/Build/Documentation/ImageryLayer.html?classFilter=ImageryLayer#show)文档应当使用show属性控制图层显隐。

**Comment by Luxcy** [comment]
谢谢~我又有了个新的想法
我是通过visibility来控制style里面的layer的显隐的
如果每次控制通过visibility控制显隐后，再用show属性来关开一次，是不是就不会出现残留了。
我去试一试

**Comment by Luxcy** [comment]
谢谢~我又有了个新的想法
我是通过visibility来控制style里面的layer的显隐的
如果每次控制通过visibility控制显隐后，再用show属性来关开一次，是不是就不会出现残留了。
我去试一试
