### ISSUE TITLE
如何编译Mapbox-vector-tiles-basic-js-renderer

### ISSUE THREAD

**Issue by Luxcy** [kikitte/MVTImageryProvider#5]
你好，最近在学习这个项目的代码，想在此基础上，进行源码修改。
但在编译Mapbox-vector-tiles-basic-js-renderer遇到了些问题，引入自己打包后的文件会报错

![6d860a01daa0b50f1d006ac5f1a95c1](https://user-images.githubusercontent.com/13784184/140283805-21dc7ee9-89f3-44df-8f59-f37be3e6913a.png)

希望能获得帮助。

我们的编译过程为：

yarn install

yarn run start-debug

**Comment by Luxcy** [comment]
而且，发现将Mapbox-vector-tiles-basic-js-renderer的mapbox-gl.js去替换MVTImageryProvider的mapbox-gl.js文件后，也是无法正常显示矢量的。

谢谢~~

**Comment by kikitte** [comment]
landtechnologies提供的Mapbox-vector-tiles-basic-js-renderer直接用来渲染存在一些问题，这个项目里面用到的mapbox-gl.js是修改过的，代码放在这个仓库里https://github.com/kikitte/Mapbox-vector-tiles-basic-js-renderer

```bash
# Note:打包步骤
npm install
npx webpack
```
