### ISSUE TITLE
运行demo报这个

### ISSUE THREAD

**Issue by lishulincug** [kikitte/MVTImageryProvider#6]
![image](https://user-images.githubusercontent.com/13003282/140298973-de1d6a42-8e12-42cd-b053-2f663d4f96ea.png)

**Comment by kikitte** [comment]
无法复现，需要提供更详细的使用信息。

**Comment by lishulincug** [comment]
是配置错引起的，并且这个example样式读取不了地图
![image](https://user-images.githubusercontent.com/13003282/140450510-f6d3a367-9cd7-4a52-8167-e73cddc8df55.png)

我另外shez设置自定义的geoserver mvt瓦片可以读取吗，这边配置地址后读取不出地图
![image](https://user-images.githubusercontent.com/13003282/140450575-3136068b-ec2e-49eb-b652-a7edc4757b31.png)

**Comment by kikitte** [comment]
报错依然无法复现。example-style无法加载可能是网络环境问题，需要挂vpn。

第二张图里的composite source中出现的这个数据源由于访问了mapbox提供的地图瓦片数据，需要提供mapbox access token，不然无法访问该类数据。可在使用MVTImageryProvider之前如下操作以配置该token：
```
import Mapbox from 'cesium-mvtimageryprovider/src/mapbox-gl'
// ......
Mapbox.accessToken = "<你的Mapbox access token>";
