### ISSUE TITLE
请求策略上有优化吗，这个加载的地图有时很久才刷新，出现马赛克情况

### ISSUE THREAD

**Issue by lishulincug** [kikitte/MVTImageryProvider#7]
比如缓存，按需请求
![image](https://user-images.githubusercontent.com/13003282/142587950-c4011548-5839-4d10-8810-95a02f0f9e71.png)

**Comment by kikitte** [comment]
要排查这种加载慢的原因，根据目前提供的信息不足以判断。从你的描述上看，感觉更可能是网络缓慢而不是渲染缓慢。从我的尝试上看，网络正常的情况下加载一般几秒就可以渲染完毕。

**Comment by lishulincug** [comment]
> 
![image](https://user-images.githubusercontent.com/13003282/142992709-aab6d06b-bb49-43aa-ad80-9164cd3fc9ea.png)
放大到17级以上很多报400，
我用自己发的geoserver的mvt服务，最大最小级别为0-18级，放到17级以上也报400的多，有部分总是出现马赛克，再放大点就消失。
![image](https://user-images.githubusercontent.com/13003282/142993549-e6b4189f-4143-473f-a4e9-bd8c8ab57e8a.png)

**Comment by lishulincug** [comment]
这里通过mapbox请求渲染后再显示到cesium中，之前看有先通过url请求，再用ol解析pdf和渲染，后通过canvs展示在cesium中，看速度还行。
function  requestImage  (x, y, level, request) {
    var cacheTile = findTileInQueue(x, y, level, this._tileQueue)
    if (cacheTile != undefined) {
      return cacheTile
    } else {
      var that = this
      var url = this._url

      var reverseY = this._tilingScheme.getNumberOfYTilesAtLevel(level) - y - 1
      url = this._key != '' ? url.replace('{x}', x).replace('{y}', y).replace('{reverseY}', reverseY).replace('{z}', level).replace('{k}', this._key): url.replace("{x}", x).replace("{y}", y).replace("{z}", level);

      var resource = BOSGeo.Resource.createIfNeeded(url)
      return resource
        .fetchArrayBuffer()
        .then(function (arrayBuffer) {
          var canvas = document.createElement('canvas')
          canvas.width = that._tileWidth
          canvas.height = that._tileHeight
          var vectorContext = canvas.getContext('2d')

          var features = that._mvtParser.readFeatures(arrayBuffer)

          var styleFun = that._styleClass.getStyle ? that._styleClass.getStyle(): that._styleClass

          var extent = [0, 0, 4096, 4096]
          var _replayGroup = new ol.render.canvas.ReplayGroup(0, extent, 8, true, 100)

          for (var i = 0; i < features.length; i++) {
            var feature = features[i]
            var styles = styleFun(features[i], that._resolutions[level])
            for (var j = 0; j < styles.length; j++) {
              ol.renderer.vector.renderFeature_(_replayGroup, feature, styles[j], 16)
            }
          }
          _replayGroup.finish()

          _replayGroup.replay(vectorContext, that._pixelRatio, that._transform, 0, {}, that._replays, true)
          if (that._tileQueue.count > that._cacheSize) {
            trimTiles(that._tileQueue, that._cacheSize / 2)
          }

          canvas.xMvt = x
          canvas.yMvt = y
          canvas.zMvt = level
          that._tileQueue.markTileRendered(canvas)

          delete _replayGroup
          _replayGroup = null

          return canvas
        })
        .otherwise(function (error) {
          return undefined
        })
    }
  }

**Comment by kikitte** [comment]
maptiler这个样式的瓦片数据源最高层级应该是16,所以到了更高层级无法渲染，变”糊“、出现400状态码是正常结果。要解决 渲染geoserver mvt服务出现马赛克 这个问题 需要先确认 出现马赛克的瓦片 是否 能够请求到？如果能够请求到则表明是mapbox渲染的原因：渲染不出来了，如果不能够请求到相应瓦片则应先解决GeoServer的问题。
可以修改mapbox-gl.js里面showTileBoundaries为true，这样可以在渲染瓦片时附带上瓦片坐标，方便定位瓦片。
![image](https://user-images.githubusercontent.com/23274684/143054882-108a3e7f-38db-45c2-b5e4-d93bde52d06b.png)

![image](https://user-images.githubusercontent.com/23274684/143054763-68a3aad3-7061-4bca-910f-7f66c835f694.png)

**Comment by lishulincug** [comment]
![image](https://user-images.githubusercontent.com/13003282/143193379-7d147328-9a33-4521-99b7-9d85fdf73edf.png)
把this.tileSize设为2048后，部分区域出现马赛克的情况减少，但有时会报DeveloperError: Expected width to be greater than 0, actual value was 0。
之前的this.tileSize设为512，推断基于mvt渲染，mvt本身有tile，一般是256，是每次canvas更新的mvt瓦片太少，引起的吧，我用上面的ol加载mvt没有出现很多马赛克情况。当然也会有400报出

**Comment by ShangXiaoYun** [comment]
> 这里通过mapbox请求渲染后再显示到cesium中，之前看有先通过url请求，再用ol解析pdf和渲染，后通过canvs展示在cesium中，看速度还行。 function requestImage (x, y, level, request) { var cacheTile = findTileInQueue(x, y, level, this._tileQueue) if (cacheTile != undefined) { return cacheTile } else { var that = this var url = this._url
> 
> ```
>   var reverseY = this._tilingScheme.getNumberOfYTilesAtLevel(level) - y - 1
>   url = this._key != '' ? url.replace('{x}', x).replace('{y}', y).replace('{reverseY}', reverseY).replace('{z}', level).replace('{k}', this._key): url.replace("{x}", x).replace("{y}", y).replace("{z}", level);
> 
>   var resource = BOSGeo.Resource.createIfNeeded(url)
>   return resource
>     .fetchArrayBuffer()
>     .then(function (arrayBuffer) {
>       var canvas = document.createElement('canvas')
>       canvas.width = that._tileWidth
>       canvas.height = that._tileHeight
>       var vectorContext = canvas.getContext('2d')
> 
>       var features = that._mvtParser.readFeatures(arrayBuffer)
> 
>       var styleFun = that._styleClass.getStyle ? that._styleClass.getStyle(): that._styleClass
> 
>       var extent = [0, 0, 4096, 4096]
>       var _replayGroup = new ol.render.canvas.ReplayGroup(0, extent, 8, true, 100)
> 
>       for (var i = 0; i < features.length; i++) {
>         var feature = features[i]
>         var styles = styleFun(features[i], that._resolutions[level])
>         for (var j = 0; j < styles.length; j++) {
>           ol.renderer.vector.renderFeature_(_replayGroup, feature, styles[j], 16)
>         }
>       }
>       _replayGroup.finish()
> 
>       _replayGroup.replay(vectorContext, that._pixelRatio, that._transform, 0, {}, that._replays, true)
>       if (that._tileQueue.count > that._cacheSize) {
>         trimTiles(that._tileQueue, that._cacheSize / 2)
>       }
> 
>       canvas.xMvt = x
>       canvas.yMvt = y
>       canvas.zMvt = level
>       that._tileQueue.markTileRendered(canvas)
> 
>       delete _replayGroup
>       _replayGroup = null
> 
>       return canvas
>     })
>     .otherwise(function (error) {
>       return undefined
>     })
> }
> ```
> 
> }

您好，您的这段代码我在下载的代码中没有找到，请问您有相关的资料吗？或者您的代码可以分享一下吗？另外如何得到未压缩的mapbox-gl.js脚本文件，您能教教我吗？期待您的回复！

**Comment by ShangXiaoYun** [comment]
> 这里通过mapbox请求渲染后再显示到cesium中，之前看有先通过url请求，再用ol解析pdf和渲染，后通过canvs展示在cesium中，看速度还行。 function requestImage (x, y, level, request) { var cacheTile = findTileInQueue(x, y, level, this._tileQueue) if (cacheTile != undefined) { return cacheTile } else { var that = this var url = this._url
> 
> ```
>   var reverseY = this._tilingScheme.getNumberOfYTilesAtLevel(level) - y - 1
>   url = this._key != '' ? url.replace('{x}', x).replace('{y}', y).replace('{reverseY}', reverseY).replace('{z}', level).replace('{k}', this._key): url.replace("{x}", x).replace("{y}", y).replace("{z}", level);
> 
>   var resource = BOSGeo.Resource.createIfNeeded(url)
>   return resource
>     .fetchArrayBuffer()
>     .then(function (arrayBuffer) {
>       var canvas = document.createElement('canvas')
>       canvas.width = that._tileWidth
>       canvas.height = that._tileHeight
>       var vectorContext = canvas.getContext('2d')
> 
>       var features = that._mvtParser.readFeatures(arrayBuffer)
> 
>       var styleFun = that._styleClass.getStyle ? that._styleClass.getStyle(): that._styleClass
> 
>       var extent = [0, 0, 4096, 4096]
>       var _replayGroup = new ol.render.canvas.ReplayGroup(0, extent, 8, true, 100)
> 
>       for (var i = 0; i < features.length; i++) {
>         var feature = features[i]
>         var styles = styleFun(features[i], that._resolutions[level])
>         for (var j = 0; j < styles.length; j++) {
>           ol.renderer.vector.renderFeature_(_replayGroup, feature, styles[j], 16)
>         }
>       }
>       _replayGroup.finish()
> 
>       _replayGroup.replay(vectorContext, that._pixelRatio, that._transform, 0, {}, that._replays, true)
>       if (that._tileQueue.count > that._cacheSize) {
>         trimTiles(that._tileQueue, that._cacheSize / 2)
>       }
> 
>       canvas.xMvt = x
>       canvas.yMvt = y
>       canvas.zMvt = level
>       that._tileQueue.markTileRendered(canvas)
> 
>       delete _replayGroup
>       _replayGroup = null
> 
>       return canvas
>     })
>     .otherwise(function (error) {
>       return undefined
>     })
> }
> ```
> 
> }

您好，您的这段代码我在下载的代码中没有找到，请问您有相关的资料吗？或者您的代码可以分享一下吗？另外如何得到未压缩的mapbox-gl.js脚本文件，您能教教我吗？期待您的回复！

**Comment by jiuxs33** [comment]
地图数据源是mbtiles，地图最大层级是14级。 这样的话访问地图超过14级，地图就模糊了。并且还遇到了地图背景图层 没有效果

**Comment by kikitte** [comment]
> 地图数据源是mbtiles，地图最大层级是14级。 这样的话访问地图超过14级，地图就模糊了。并且还遇到了地图背景图层 没有效果

访问超过14级别会糊由CesiumJS控制，所以这个应该无能为力。不支持背景图层，或许以后有动力会花时间看下，但不是现在。

**Comment by kikitte** [comment]
关闭。如果想解决问题请按照以上讨论提供完整信息而不是凭借猜测，然后在重新开一个问题。
