### ISSUE TITLE
如何获取未压缩的mapbox-gl.js?

### ISSUE THREAD

**Issue by ShangXiaoYun** [kikitte/MVTImageryProvider#8]
您好，您的代码中mapbox-gl.js脚本库经过压缩了，调试和阅读源码比较困难。但是由于不熟悉mapbox，我没有找到未压缩的mapbox-gl.js，向您请教方法，期待您的回复。

**Comment by kikitte** [comment]
https://github.com/kikitte/Mapbox-vector-tiles-basic-js-renderer
