### ISSUE TITLE
mapbox 1.13.1的样式文件不可用啊

### ISSUE THREAD

**Issue by jiuxs33** [kikitte/MVTImageryProvider#9]

**Comment by kikitte** [comment]
嘿，为了解决这个问题，你需要提供无法加载的样式文件并描述当前软件的表现以及你所期望的表现，简而言之就是让别人能够复现并知晓到底发生了什么事。

**Comment by jiuxs33** [comment]
错误 layers[30].filter[2]: Expected arguments of type (number, number) | (string, string), but found (value, number) instead.
样式设置： 
{
    "id": "town-label",
    "type": "symbol",
    "source": "composite",
    "source-layer": "place",
    "metadata": {
        "name": "乡镇街道"
    },
    "minzoom": 13,
    "maxzoom": 19,
    "filter": [
        "all",
        [
            "==",
            [
                "get",
                "class"
            ],
            "town"
        ]
    ],
    "layout": {
        "text-size": 13,
        "text-font": [
            "KlokanTech Noto Sans CJK Bold"
        ],
        "text-field": "{name:nonlatin}",
        "text-letter-spacing": 0.15,
        "text-max-width": 6
    },
    "paint": {
        "text-color": "#000000",
        "text-halo-color": "#ffffff",
        "text-halo-width": 0.8,
        "icon-halo-color": "#ffffff",
        "icon-color": "#333333"
    }
}

**Comment by kikitte** [comment]
从提供的报错信息来看，出错的地方为Layer的filter属性，该属性为一返回布尔值的表达式。例子中，该处涉及到mapbox style的三个表达式：[all](https://docs.mapbox.com/mapbox-gl-js/style-spec/expressions/#all)、[==](https://docs.mapbox.com/mapbox-gl-js/style-spec/expressions/#==)、[get](https://docs.mapbox.com/mapbox-gl-js/style-spec/expressions/#get)。从mapbox style specification官方网站提供的信息可知，all、==和get 要求mapbox gljs 版本大于>= 0.41.0。当前Mapbox-basic-renderer对应的mapbox gljs版本为 [0.43.0](https://github.com/landtechnologies/Mapbox-vector-tiles-basic-js-renderer/commit/fa54d3d769013e5b3f24de26f88d1cb61cd7b339#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519)，可知完全支持上述样例中的filter表达式，另外我经过测试也证明了这一点。

结合出错信息和样例来看，报错信息对应的图层不是给的样例图层，原因在于”town"并非number类型。

所以该问题我更倾向于==表达式中 矢量瓦片要素属性类型和 第二个用于比较的参数类型不一致导致，并非Mapbox-basic-render的原因。

**Comment by jiuxs33** [comment]
好的 我再看一下，谢谢
